### ISSUE TITLE
程序运行首页白屏

### ISSUE THREAD

**Issue by cybkw** [alibaba/flutter-common-widgets-app#12]
[ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
FileSystemException: Cannot open file, path = '/data/user/0/com.example.flutterrookiebook/databases/flutter.db' (OS Error: No such file or directory, errno = 2)
 #0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
E/flutter (17009): #1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
E/flutter (17009): #2      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
E/flutter (17009): #3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
E/flutter (17009): #4      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
E/flutter (17009): #5      Future._completeWithValue (dart:async/future_impl.dart:486:5)
E/flutter (17009): #6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
E/flutter (17009): #7      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (17009): #8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by imlida** [comment]
testflight安装后启动白屏

**Comment by hanxu317317** [comment]
请清除本地缓存后. 拉取最新master代码.  我们已经在master中试图解决兼容的问题.

**Comment by hanxu317317** [comment]
@imlida @cybkw 期待您的反馈.

**Comment by imlida** [comment]
@hanxu317317 android已正常，但testflight测试还是白屏
